### ISSUE TITLE
Empty advertisement blocks on some pages

### ISSUE THREAD

**Issue by andyg21** [illogical-robot/apkmirror-public#228]
#### Expected behavior
Filled advertisement blocks

#### Actual behavior
Empty advertisement blocks
![image](https://user-images.githubusercontent.com/67194650/181677707-ba770b4f-e702-4483-a4e1-019d8a6ac652.png)

#### Steps to reproduce the problem
Visit
https://www.apkmirror.com/apk/kinemaster-corporation/kinemasterpro-video-editor/kinemasterpro-video-editor-6-0-6-26410-gp-release/

**Comment by archon810** [comment]
I think this is due to things like this https://notifications.google.com/g/p/APNL1Th320_C6_14awbkJEvmgod8BYeQ19JDqwMkfJECdgXInv-GKK0stkHrRFmEFk3ugei5OuvAbMDBgQiR3ufZd2P7WcrhX8pMa6S-ghY8E5GVbYQNgnkqcQYEPhIO9nk736E-fco which Google then applies to Adsense in some cases. So they block advertising on certain pages as a result. Nothing we can do really.
