### ISSUE TITLE
The version in the Variant column is wrong.

### ISSUE THREAD

**Issue by k5746** [illogical-robot/apkmirror-public#235]
On any app page, under the `ALL VARIANTS` tab, the latest version shown in the `Variant` column is actually the oldest.

**Comment by archon810** [comment]
You seem to be right. For example: https://www.apkmirror.com/apk/google-inc/analytics/#variants

(arm64-v8a) (nodpi) (Android 4.4+)
Latest: 4.0.329364267 on August 31, 2020 PDT

But https://www.apkmirror.com/apk/google-inc/analytics/variant-%7B%22arches_slug%22%3A%5B%22arm64-v8a%22%5D%2C%22dpis_slug%22%3A%5B%22nodpi%22%5D%2C%22minapi_slug%22%3A%22minapi-19%22%7D/ shows many versions after.

Thank you for reporting, we'll figure out where the bug came from and push out a fix.

**Comment by archon810** [comment]
The issue has been fixed. For example, Analytics:
![image](https://user-images.githubusercontent.com/469543/189976181-7c270ee8-9da9-498e-8e1c-587af4ff4bdd.png)

We're going to need to reprocess all the app cache, which I'll kick off now. Please report back if you see any more errors after a couple of hours.
