### ISSUE TITLE
Advanced Search Bug?

### ISSUE THREAD

**Issue by Nzzyme** [illogical-robot/apkmirror-public#241]
#### Expected behavior
There should be a search box / text field where we can input the search term/keyword when performing an 'Advanced Search'.

#### Actual behavior
There is no search box when clicking on the 'Advanced Search' icon

#### Steps to reproduce the problem

1. Visit https://www.apkmirror.com/
2. Click on the 'Advanced Search' icon directly in the main search box. This brings up the Advanced Search options.
3. Select 'Capabilities' as 'Android TV'.
4. Input 'MagellanTV' in the search box and click on the 'Apply' button
5. The results should only show the variants which are 'Android TV' compatible but it shows other variants as well.

Screenshot: 

![image](https://user-images.githubusercontent.com/6959116/208048922-2de2ebc2-23a3-4aa8-868a-ad2b0ca4ecb8.png)

**Comment by archon810** [comment]
The main search box is used for advanced search, like in your screenshot.

As for the specific issue you're referencing with [MagellanTV and Android TV](https://www.apkmirror.com/?post_type=app_release&searchtype=apk&s=magellantv&cap%5B%5D=leanback), the reason both results come up is because the Android TV app has "Requires Android TV" while the regular app still supports it ("Supports Android TV"). Therefore, both apps support Android TV and are therefore shown.
