### ISSUE TITLE
Installed apk does not appear on app menu

### ISSUE THREAD

**Issue by DJGroovin** [illogical-robot/apkmirror-public#282]
#### Expected behavior
Installing the paramount plus usa apkm file.  App then appears on launcher screen and is recognized under play store when you check manage installed apps.

#### Actual behavior
App.will launch from post install screen asking if you want to open it.  However there is no other way beyond this to open the app as it's not being appealing to the android tv app launcher, and can't be found under play stores manage installed apps.  The app is here but nothing points to it so I can't open it.

**Comment by archon810** [comment]
The only way this would happen, to my knowledge, is if the Paramount app is pre-installed on your device. Regardless, however, this issue tracker is not meant for issues with individual third party apps, so I'm going to close the ticket.

Out of curiosity, what device are you using? Are you able to install the regular APK file instead of the apkm and see if it exhibits a different behavior?

**Comment by DJGroovin** [comment]
This is happening on an android tv stream.box provided by my internet / tv provider.  It's obviously something else rebadge as bell fibe vip7802...looks like its made by arris.

Version 10
Kernel version 4.9.295-1-19

I haven't tried the apk file on its own...i will try that now.   It's definitely not preloaded.  There is two versions of the paramount plus app, a Canadian one and an American one and they are different...this would not have the American app preloaded.



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
